"""add_notes_nonce_to_password_entries

Revision ID: 249185c745ec
Revises: ac50e4596c59
Create Date: 2026-08-27 09:47:44.761466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '249185c745ec'
down_revision: Union[str, None] = 'ac50e4596c59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_entries', sa.Column('notes_nonce', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('password_entries', 'notes_nonce')
    # ### end Alembic commands ###
