"""add_vault_kdf_salt_to_users

Revision ID: bde94970495a
Revises: 249185c745ec
Create Date: 2026-08-28 09:38:57.665364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bde94970495a'
down_revision: Union[str, None] = '249185c745ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vault_kdf_salt', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'vault_kdf_salt')
    # ### end Alembic commands ###
